const express = require("express");
const router = express.Router();
const user_controller = require("../controller/user_controller");
router.get("/", user_controller.user);
router.get("/profile", user_controller.profile);
router.get("/sign-in", user_controller.signin);
router.get("/sign-up", user_controller.signup);
router.post("/create", user_controller.create);
router.post("/create-session", user_controller.create_session);
router.get("/sign-out", user_controller.destroy_session);
module.exports = router;
